### ISSUE TITLE
Unlisted dependencies issue for Yarn 2+ users

### ISSUE THREAD

**Issue by legowerewolf** [storacha/w3name#101]
```
PS > yarn node
Welcome to Node.js v20.4.0.
Type ".help" for more information.
> const Name = import('w3name')
undefined
> Uncaught:
Error: w3name tried to access multiformats, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: multiformats (via "multiformats\hashes\identity")
Required by: w3name@npm:1.0.8 (via \.yarn\cache\w3name-npm-1.0.8-0d4552a104-02dc258667.zip\node_modules\w3name\dist\index.mjs)

    at makeError (\.pnp.cjs:15361:34)
    at resolveToUnqualified (\.pnp.cjs:17088:21)
    at resolveRequest (\.pnp.cjs:17217:31)
    at Object.resolveRequest (\.pnp.cjs:17280:26)
    at resolve$1 (/.pnp.loader.mjs:1989:21)
    at nextResolve (node:internal/modules/esm/hooks:733:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:242:30)
    at handleMessage (node:internal/modules/esm/worker:168:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:117:28)
    at process.processImmediate (node:internal/timers:478:21)
```

Suggest using [`@yarnpkg/doctor`](https://yarnpkg.com/api/modules/yarnpkg_doctor.html) to resolve issue(s).

**Comment by alanshaw** [comment]
Resolved by https://github.com/storacha/w3name/pull/103
